#!/bin/bash
#
# install tarballs. Containers corr profile uses wget to get this file to exec.
#
#TARBALL_LOC="http://lxd110maas.ovro.pvt/maas/config/tarballs"
TARBALL_LOC="http://10.42.0.3/maas/config/tarballs"

cd /usr/local
wget $TARBALL_LOC/go1.12.6.linux-amd64.tar.gz
tar xf go1.12.6.linux-amd64.tar.gz
mv go go1.12.6
ln -s go1.12.6 go
#wget https://github.com/thrust/thrust/archive/1.8.1.tar.gz
wget $TARBALL_LOC/thrust-1.8.1.tar.gz
tar xf thrust-1.8.1.tar.gz
#wget http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio-3.47.tar.gz
wget $TARBALL_LOC/cfitsio-3.47.tar.gz
tar xf cfitsio-3.47.tar.gz
cd cfitsio-3.47 && ./configure && make -j30 install && cd -
#wget https://download.open-mpi.org/release/hwloc/v2.1/hwloc-2.1.0.tar.gz
wget $TARBALL_LOC/hwloc-2.1.0.tar.gz
tar xf hwloc-2.1.0.tar.gz
cd hwloc-2.1.0 && ./configure && make -j30 install && cd -
#wget http://www.iausofa.org/2019_0722_C/sofa_c-20190722.tar.gz
wget $TARBALL_LOC/sofa_c-20190722.tar.gz
tar xf sofa_c-20190722.tar.gz
cd sofa/20190722/c/src && make && make test && cd -
#wget http://www.fftw.org/fftw-3.3.8.tar.gz
wget $TARBALL_LOC/fftw-3.3.8.tar.gz
tar xf fftw-3.3.8.tar.gz
# install with --enable-float --enable-shared
cd fftw-3.3.8 && ./configure --enable-float --enable-shared && make -j30 install && cd -
# dedisp from dsahead
wget $TARBALL_LOC/dedisp.tar
tar -xvf dedisp.tar
cd dedisp && make clean && make && make install && cd -

# labjack libs
cd /usr/local
wget $TARBALL_LOC/labjack_ljm_software_2017_01_02_x86_64.tar_0.gz
tar xf labjack_ljm_software_2017_01_02_x86_64.tar_0.gz
cd labjack_ljm_software_2017_01_02_x86_64
USER=root ./labjack_ljm_installer.run

