#!/bin/bash

# Set sysctl parameters for 40Gb Mellanox cards
## kernal
vars='kernel.shmmax=68719476736'
vars+=' kernel.shmall=4294967296'

SYSCTLFN=/etc/sysctl.conf

# net.ipv4
vars+=' net.ipv4.conf.all.rp_filter=0'
vars+=' net.ipv4.tcp_timestamps=0'
vars+=' net.ipv4.tcp_sack=0'
vars+=' net.ipv4.tcp_low_latency=1'
vars+=' net.ipv4.tcp_adv_win_scale=1'

# net.cor
vars+=' net.core.netdev_max_backlog=250000'
vars+=' net.core.rmem_max=536870912'
vars+=' net.core.wmem_max=536870912'
vars+=' net.core.rmem_default=16777216'
vars+=' net.core.wmem_default=16777216'
vars+=' net.core.optmem_max=16777216'

echo "updating system parameter and /etc/sysctl.conf"
for var in $vars; do
    echo "$var"
    sysctl -w $var
    echo $var >> $SYSCTLFN
done

# can't get shell to treat as a group
echo 'net.ipv4.tcp_mem="16777216 16777216 16777216"'
sysctl -w net.ipv4.tcp_mem="16777216 16777216 16777216"
echo 'net.ipv4.tcp_mem="16777216 16777216 16777216"' >> $SYSCTLFN

echo 'net.ipv4.tcp_rmem="4096 87380 16777216"'
sysctl -w net.ipv4.tcp_rmem="4096 87380 16777216"
echo 'net.ipv4.tcp_rmem="4096 87380 16777216"' >> $SYSCTLFN

echo 'net.ipv4.tcp_wmem="4096 87380 16777216"'
sysctl -w net.ipv4.tcp_wmem="4096 87380 16777216"
echo 'net.ipv4.tcp_wmem="4096 87380 16777216"' >> $SYSCTLFN
